theme: jekyll-theme-cayman
title: Analysis of Renewable Energy Development in the US
description: Using machine learning techniques to analyze the significance of factors affecting renewable energy development in the US.